### ISSUE TITLE
Add the name of the volume to be removed in the confirmation popup

### ISSUE THREAD

**Issue by benja-M-1** [docker/volumes-backup-extension#67]
**Is your feature request related to a problem? Please describe.**
I removed a first and immediately after confirming I click on another line to remove another. In the meantime, a line disappeared, I guess the one from the removed volume, and I wasn't sure I clicked on the right one anymore.

**Describe the solution you'd like**
Add the name of the volume in the popup

**Describe alternatives you've considered**
I closed the popup, do it again

**Additional context**

<img width="1382" alt="Screenshot 2022-09-13 at 11 44 29" src="https://user-images.githubusercontent.com/212269/189869413-aaf3c7e1-cf23-48bf-a5c6-d2a8074ed874.png">

**Comment by felipecruz91** [comment]
This is now available in `1.1.0`.
