### ISSUE TITLE
Don't start stopped containers when cloning a volume

### ISSUE THREAD

**Issue by felipecruz91** [docker/volumes-backup-extension#91]
**Describe the bug**
When you clone a volume of a stopped container that container starts automatically. I think this may be dangerous without a warning and without allowing to avoid such start of the stopped container.

**Add the steps to reproduce**

**Describe the expected behavior**

**Optional: Add screenshots**

**Output of `docker extension version`:**

```
(paste your output here)
```

**Output of `docker version`:**

```
(paste your output here)
```

**Include extension console logs**
If relevant, you can add console logs that might include some trace related to the bug you're reporting

**Additional context**

**Comment by SscSPs** [comment]
Hi, Can you elaborate a bit?
I was going through this project and saw your issue so decided to take a look, from my little bit of investigation, I found it should be working as expected, i.e. stop any running container and don't start any stopped container.

[this](https://github.com/docker/volumes-backup-extension/blob/main/vm/internal/handler/clone.go#L62) line says that it needs to stop running containers, so containers are stopped, and not started

Can you share version number and some steps to reproduce?

**Comment by felipecruz91** [comment]
Hi @SscSPs, apparently that function is retrieve _all_ the containers attached to a volume, instead of the _stopped_ ones, see: https://github.com/docker/volumes-backup-extension/blob/915c5754ab43d6897690c5bb7d8a7640636cb211/vm/internal/backend/containers.go#L43

The following must be changed in order to retrieve only the _stopped_ containers:

https://github.com/docker/volumes-backup-extension/blob/915c5754ab43d6897690c5bb7d8a7640636cb211/vm/internal/backend/containers.go#L22-L25 

We could extend it by defining a new `filters.Arg` to filter by _stopped_ containers.

**Comment by SscSPs** [comment]
Okay, got it, I did not follow through the whole code before getting confused, 
https://github.com/docker/volumes-backup-extension/blob/915c5754ab43d6897690c5bb7d8a7640636cb211/vm/internal/handler/clone.go#L153
here we are starting the stopped containers, and stopped containers may also contain ones that were already stopped before clone call.

I'll raise a PR with filters soon, 
assign this to me if possible :)

**Comment by SscSPs** [comment]
@felipecruz91 created a PR, please review
