### ISSUE TITLE
Extension “Volumes Backup & Share” fails with “Internal Server Error HTTP status code: 500”

### ISSUE THREAD

**Issue by TheSwede86** [docker/volumes-backup-extension#97]
Issue type: Unable to backup volume using extension “Volumes Backup & Share”
OS Version / Build: Windows 11 Version 22H2 (Build: 22621.674)
App version: v.4.13.1
Steps to reproduce:
“Volumes Backup & Share” > “Export volume” > “To: Local File” > “.tar.zst” > “Directory” > “Select directory” > “” returns
Failed to backup volume to C:\Users<my-win-user>\Desktop: {“message”:“Internal Server Error”}. HTTP status code: 500

Diagnostic ID:
6FD65E53-DD8F-44DB-A774-357A2EE71651/20221102203305

Hello,

Trying to export a volume using the Docker extension “Volumes Backup & Share” but it fails regardless of destination:
C:
C:\Users<my-win-user>\Desktop
D:\
^ External USB
with the error:
Failed to backup volume to C:\Users<my-win-user>\Desktop: {“message”:“Internal Server Error”}. HTTP status code: 500

The container the volume belongs to isn’t started.

Would appreciate any and all help!

Best Regards - TheSwede86

**Comment by felipecruz91** [comment]
Hi @TheSwede86, thank you for reporting this issue.

Could you attach a text file with the logs of the extension container? (i.e. `docker logs docker_volumes-backup-extension-desktop-extension-service`)

If you don't see that container, enable the Extension systems containers option in Preferences > Extensions.

**Comment by TheSwede86** [comment]
> After some investigation, I think this may be the error you're seeing:
> 
> `errdefs.errInvalidParameter Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/c/openstreetmap-tile-server/sweden-latest/sweden-latest.osm.pbf" to rootfs at "/data/region.osm.pbf": mount /run/desktop/mnt/host/c/openstreetmap-tile-server/sweden-latest/sweden-latest.osm.pbf:/data/region.osm.pbf (via /proc/self/fd/14), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`
> 
> Could you confirm it?

Thanks for your reply and advice!
I changed the path from:
`C:\openstreetmap-tile-server\sweden-latest\sweden-latest.osm.pbf`
to
`C:\openstreetmap-tile-server\sweden-latest.osm.pbf`
but before that I deleted the volume "osm-data", the container and the image and re-ran everything and it worked now!

Thanks again, I'll close
